name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/derl:latest
          build-args: |
            PARENT_IMAGE=ubuntu:16.04
            TORCH=cpuonly
            USER_ID=1
